# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocalArchive.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12LocalArchive.proto\x12\x13signal.backup.local\"\x94\x01\n\x08Metadata\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x41\n\x08\x62\x61\x63kupId\x18\x02 \x01(\x0b\x32/.signal.backup.local.Metadata.EncryptedBackupId\x1a\x34\n\x11\x45ncryptedBackupId\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x13\n\x0b\x65ncryptedId\x18\x02 \x01(\x0c\")\n\nFilesFrame\x12\x13\n\tmediaName\x18\x01 \x01(\tH\x00\x42\x06\n\x04itemB4\n\x1eorg.signal.archive.local.proto\xba\x02\x11LocalBackupProto_b\x06proto3')



_METADATA = DESCRIPTOR.message_types_by_name['Metadata']
_METADATA_ENCRYPTEDBACKUPID = _METADATA.nested_types_by_name['EncryptedBackupId']
_FILESFRAME = DESCRIPTOR.message_types_by_name['FilesFrame']
Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {

  'EncryptedBackupId' : _reflection.GeneratedProtocolMessageType('EncryptedBackupId', (_message.Message,), {
    'DESCRIPTOR' : _METADATA_ENCRYPTEDBACKUPID,
    '__module__' : 'LocalArchive_pb2'
    # @@protoc_insertion_point(class_scope:signal.backup.local.Metadata.EncryptedBackupId)
    })
  ,
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'LocalArchive_pb2'
  # @@protoc_insertion_point(class_scope:signal.backup.local.Metadata)
  })
_sym_db.RegisterMessage(Metadata)
_sym_db.RegisterMessage(Metadata.EncryptedBackupId)

FilesFrame = _reflection.GeneratedProtocolMessageType('FilesFrame', (_message.Message,), {
  'DESCRIPTOR' : _FILESFRAME,
  '__module__' : 'LocalArchive_pb2'
  # @@protoc_insertion_point(class_scope:signal.backup.local.FilesFrame)
  })
_sym_db.RegisterMessage(FilesFrame)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036org.signal.archive.local.proto\272\002\021LocalBackupProto_'
  _METADATA._serialized_start=44
  _METADATA._serialized_end=192
  _METADATA_ENCRYPTEDBACKUPID._serialized_start=140
  _METADATA_ENCRYPTEDBACKUPID._serialized_end=192
  _FILESFRAME._serialized_start=194
  _FILESFRAME._serialized_end=235
# @@protoc_insertion_point(module_scope)
